[build]
  # Build command
  command = "pnpm build"
  
  # Directory with the static site files
  publish = "out"
  
  # Functions directory (if using Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Enable pnpm
  NPM_FLAGS = "--version"
  
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if you have contact forms)
# [[headers]]
#   for = "/api/*"
#   [headers.values]
#     Access-Control-Allow-Origin = "*"
#     Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
#     Access-Control-Allow-Headers = "Content-Type, Authorization"

# Environment-specific settings
[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"
